# Generated by Django 4.0.5 on 2022-09-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_product_date_alter_product_des_alter_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='sub_category',
        ),
    ]
