# Generated by Django 4.0.5 on 2022-09-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_mycart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
